[Feat] 좋아요 기능 추가
spam-mayo/mayo-frontend pull request #79
Opened 2023-06-13 07:06 UTC by jjeonge97

# 이 풀리퀘스트는 다음과 같습니다

## 배경

- 구인글 좋아요 기능 추가 작업 진행했습니다.

## 작업내용

- 사용자가 구인글에 좋아요를 누르고 취소할 수 있습니다.
- 좋아요 여부가 유지될 수 있습니다.
- 로그인을 하지 않은 사용자는 좋아요를 누를 수 없습니다.
- 마이페이지 > 관심 스터디에서 좋아요 누른 스터디를 조회할 수 있습니다.

로그인 한 사용자
https://github.com/spam-mayo/mayo-frontend/assets/110615050/e66f91c3-fb43-40e4-a916-8b2f5a016a83

로그인 안 한 사용자
https://github.com/spam-mayo/mayo-frontend/assets/110615050/5248be55-727f-4333-aed9-3d18fe5af1ef
## 리뷰어에게

2023-06-14 00:40 UTC, keoneokeoneo requested changes
전체적으로 수정이 필요해보이기 때문에 RC 드립니다

2023-06-14 00:40 UTC, keoneokeoneo commented on src/pages/recruit/Detail.tsx
> +  const postRecruitLike = useRecruitLikesPost(onToggleHeart);
훅 부분은 상단으로 올려서 일관적인 포맷을 유지하는게 가독성 측면에서더 좋을 것 같네요

2023-06-14 00:40 UTC, keoneokeoneo commented on src/pages/recruit/Detail.tsx
> +            <i className={`icon-heart ${isClicked ? 'clicked' : ''}`} onClick={onClickHeart} />
classnames 라는 라이브러리 사용으로 바꾸는게 더 좋을 것 같습니다

2023-06-14 00:40 UTC, keoneokeoneo commented on src/queries/recruit/useRecruitLikesPost.ts
> +const useRecruitLikesPost = (onToggleHeart: () => void) => {
리액트 쿼리를 이렇게 사용하는 방식은 범용성 측면에서 좋지 않습니다.
mutation option 타입 기반으로 options 이라는 파라미터를 조건부로 받고, 호출부에서 onSuccess 콜백을 작성해주는게 더 바람직해보입니다.
(수정이 필요하다는 뜻)

2023-06-14 00:40 UTC, keoneokeoneo commented on src/queries/recruit/useRecruitLikesPost.ts
해당 뮤테이션 훅 전체적으로 수정이 필요합니다.
사실
```typescript
const useRecruitLikesPost = (options?: Options) => useMutation(postRecruitLikes, { ...your options, ...options })
export default useRecruitLikesPost;
```
이런 방식으로 작성되는게 더 바람직합니다

2023-06-14 00:40 UTC, keoneokeoneo commented on src/queries/recruit/useRecruitLikesPost.ts
추가로 get 함수를 사용하는 useQuery는 useXXXQuery 라고 통상적으로 네이밍하기 때문에, 전 mutation도 일관성을 위해 Mutation을 붙여줍니다.
ex: usePostRecruitLikesMutation

2023-06-14 00:40 UTC, keoneokeoneo commented on src/pages/recruit/Detail.tsx
> +  useEffect(() => {
데이터를 받아 왔을 때 state 변경을 하기 위해서 useEffect를 사용하신 것 같은데, 라이프 사이클 없이 구현이 가능하기 때문에 다시 검토해보시길 권장합니다

2023-06-14 00:40 UTC, keoneokeoneo commented on src/pages/user/UserLikeStudy.tsx
> +  const { data, isLoading, isError } = useQuery({
여기는 왜 query hook으로 빠지지 않았을까요?

2023-06-16 04:59 UTC, jjeonge97 commented on src/pages/user/UserLikeStudy.tsx
> +  const { data, isLoading, isError } = useQuery({
브랜치를 따로 만들어서 전체적으로 수정하려고 했습니다ㅜ

2023-06-16 05:24 UTC, jjeonge97 commented on src/queries/recruit/useRecruitLikesPost.ts
넵

2023-06-16 05:24 UTC, jjeonge97 commented on src/pages/recruit/Detail.tsx
> +  const postRecruitLike = useRecruitLikesPost(onToggleHeart);
넵 훅 수정하고 최상단으로 이동시켰습니다!

2023-06-19 04:22 UTC, merged